k = float(input("Obhvat po bustu: "))
m = float(input("Obhvat po bedram: "))
n = float(input("Obhvat po talii: "))
t = float(input("Height: "))
p = float(input("Weight: "))
l = (k*m*t)/((n**2)*p)
print(int(l))
